version: "3"
services:
  phpinfo:
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    links:
      - mariadb:mariadb
  mariadb:
    build: ./docker/mariadb
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=firststep
      - MYSQL_ROOT_PASSWORD=password
