version: "3"
services:

  phpinfo:
    build: ./
    ports:
      - "18080:80"
    networks:
      - firststepnet
    volumes:
      - .:/var/www/html
    links:
      - mariadb:mariadb

  mariadb:
    build: ./docker/mariadb
    volumes:
      - /var/data/db:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - firststepnet
    environment:
      - MYSQL_DATABASE=firststep
      - MYSQL_ROOT_PASSWORD=password

volumes:
     mariadb:
       driver: "local"

networks:
     firststepnet:
         driver: bridge
